accelerate launch examples/flux/model_training/train.py \
  --dataset_base_path /mnt/sphere/nvme-backups/luogeng/shivansh/processed_ELIGEN \
  --dataset_metadata_path /mnt/sphere/nvme-backups/luogeng/shivansh/ELIGEN_Data/caption-bboxbyqwen-dataset.jsonl \
  --data_file_keys "image,eligen_entity_masks" \
  --height 1024 \
  --width 1024 \
  --dataset_repeat 50 \
  --model_id_with_origin_paths "black-forest-labs/FLUX.1-dev:flux1-dev.safetensors,black-forest-labs/FLUX.1-dev:text_encoder/model.safetensors,black-forest-labs/FLUX.1-dev:text_encoder_2/,black-forest-labs/FLUX.1-dev:ae.safetensors" \
  --learning_rate 1e-4 \
  --steps_per_epoch 30000 \
  --num_epochs 5 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --output_path "./models/train/FLUX.1-dev-EliGen_lora" \
  --lora_base_model "dit" \
  --lora_target_modules "a_to_qkv,b_to_qkv,ff_a.0,ff_a.2,ff_b.0,ff_b.2,a_to_out,b_to_out,proj_out,norm.linear,norm1_a.linear,norm1_b.linear,to_qkv_mlp" \
  --lora_rank 16 \
  --align_to_opensource_format \
  --extra_inputs "eligen_entity_masks,eligen_entity_prompts" \
  --use_gradient_checkpointing
